# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170626_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
