# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 06:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170626_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank='True', upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numpages',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
